### ISSUE TITLE
Add to Maven Central or JCenter

### ISSUE THREAD

**Issue by cholick** [CenturyLinkCloud/clc-java-sdk#127]
Please make library available in Maven Central or JCenter

**Comment by idrabenia** [comment]
https://issues.sonatype.org/browse/OSSRH-16481

**Comment by idrabenia** [comment]
@pslam @Shkutko 

1. It would be great to implement Gradle task that allow to publish our artifacts to maven central
2. Publish current version of Java SDK to maven central. 
| Name | Value |
|---------|---------|
| Group ID | com.centurylink.cloud |
| Artifact ID | clc-java-sdk |
| Version | 1.0.0 |

**Comment by idrabenia** [comment]
This is URL to maven central nexus -  https://oss.sonatype.org 
Credentials that you provide when signed up to Sonatype JIRA must be applied for Nexus also.

**Comment by idrabenia** [comment]
@jruckle 
Done
http://search.maven.org/#search%7Cga%7C1%7Ccenturylink
