### ISSUE TITLE
git clone git@github.com:CenturyLinkCloud/clc-java-sdk.git does not work

### ISSUE THREAD

**Issue by flxstr** [CenturyLinkCloud/clc-java-sdk#130]
*This does not work*

C:\Users\mda\Development>git clone git@github.com:CenturyLinkCloud/clc-java-sdk.
git
Cloning into 'clc-java-sdk'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

*This does work*

C:\Users\mda\Development>git clone https://github.com/CenturyLinkCloud/clc-java-
sdk.git
Cloning into 'clc-java-sdk'...
remote: Counting objects: 20314, done.
remote: Total 20314 (delta 0), reused 0 (delta 0), pack-reused 20314
Receiving objects: 100% (20314/20314), 2.71 MiB | 16.00 KiB/s, done.
Resolving deltas: 100% (8816/8816), done.
Checking connectivity... done.

**Comment by jruckle** [comment]
@idrabenia can you look at this?

**Comment by idrabenia** [comment]
Hi @jruckle @flxstr !

@flxstr Could you check - do you provide you SSH public key in you Github profile. I think this is a cause of this issue.

This is detailes of required SSH configuration for working with your repo using SSH - 
https://help.github.com/articles/which-remote-url-should-i-use/

Have a good day :)
