### ISSUE TITLE
Build instructions do not work

### ISSUE THREAD

**Issue by flxstr** [CenturyLinkCloud/clc-java-sdk#131]
Following instructions from Wiki:
Build process details

$ git clone git@github.com:CenturyLinkCloud/clc-java-sdk.git
$ cd clc-java-sdk
$ gradle build

Results in:

C:\Users\mda\Development\clc-java-sdk>gradle build
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:sdk:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sdk:compileJava'.
> Could not find tools.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 13.608 secs

**Comment by push1st1k** [comment]
Hello @flxstr ,
You should install [Java SDK] (http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) and change JAVA_HOME system variable with the value of JDK location (C:\Program Files\Java\jdk1.8.x)

**Comment by jruckle** [comment]
@idrabenia  - any thoughts on this?

**Comment by idrabenia** [comment]
Hi @jruckle @push1st1k !

Yep, seems like this issue occurs because JAVA_HOME env variable relates to JRE instead of JDK.

For resolve it - I think it will great to simple install JDK and put path to it in JAVA_HOME env variable.

**Comment by jruckle** [comment]
@idrabenia has this been resolved?  please close if so
