### ISSUE TITLE
modifying a server produces NullPointerException

### ISSUE THREAD

**Issue by cljvf9** [CenturyLinkCloud/clc-java-sdk#149]
One thing I wanted to try is moving a server from one group to another. I did so by modifying the server with this piece of code:

```java
GroupMetadata group = clcSdk.groupService().find(new GroupFilter()
                .dataCenters(DataCenter.US_EAST_STERLING)
                .names("group_name")
).get(0);

clcSdk.serverService()
        .modify(
                Server.refById("server_alias"),
                new ModifyServerConfig().groupId(group.getId())
);
```

It does the move, but the API call results in a NullPointerException on ServerService.java:121

**Comment by pslam** [comment]
Hi, @cljvf9 
Do you use the latest java-sdk version ?
Now `ServerService.java:121` is `}` the end of create server method

**Comment by cljvf9** [comment]
Hi @pslam, thanks for looking into it. I just included the clc-java-sdk as a maven dependency in my project's pom. Here are the coordinates I used:

```
<dependency>
    <groupId>com.centurylink.cloud</groupId>
    <artifactId>clc-java-sdk</artifactId>
    <version>1.0.0</version>
</dependency>
```

However when I cloned the master branch from here I did not encounter the exception. Is the version in maven's central repository a bit behind?

**Comment by pslam** [comment]
Yep
I think we will update the version in maven's central repository in the near future

**Comment by cljvf9** [comment]
Cool, glad to hear it.
