### ISSUE TITLE
Policies Design Issue

### ISSUE THREAD

**Issue by idrabenia** [CenturyLinkCloud/clc-java-sdk#189]
Hi @jruckle @brianalbrecht @markramach ,

I think now we have bug in design of our SDK - 
current structure:
```
- sdk
    - loadbalancer.services
    - policy.services
    - server.services (including network management)
```
I propose to remove `policy.services` submodule and move it's functionality to server services (because this functionality highly coupled with servers).

**But this changes will break backward compatibility**

1. Are you agreed with this refactoring - **policy.services** we will move to **server.services**?
2. Will it be a big issue - if we will release this changes in next SDK version and significantly change API?

Thanks,
Ilya

**Comment by jruckle** [comment]
@idrabenia Is there a problem today, other than perhaps confusing design?  I do not recommend changing it if there is nothing functionally broken.

**Comment by idrabenia** [comment]
@jruckle yes, our API in some places provide not unified UX and we will have possibilities to improve it by this refactoring.

For instance it would be possible to make Network references API, Policy services API more user friendly.

Not a problem - current policies design and API is also acceptable but it's wrong in terms of classical design principles, may increase count of bugs in future and will surprise any users.

Yes, we may delay this refactoring until next version. But if we have possibilities to eliminate this issue now - it would be great. 

Thanks for quick response :)

**Comment by jruckle** [comment]
Closing the issue for now
