### ISSUE TITLE
Customize User Agent Header

### ISSUE THREAD

**Issue by idrabenia** [CenturyLinkCloud/clc-java-sdk#193]
***As Cloud Owner I want to track count of SDK requests by User Agent type***

It would be great to user next format of header value - 
"clc-java-sdk-v0.9" / "clc-node-sdk-v0.9" / "clc-go-cli-v0.9"

**Comment by pslam** [comment]
@idrabenia If I understand correctly we should rewrite User-Agent header.
But which value we should use ? 
Is it `clc-java-sdk-v0.9 / clc-node-sdk-v0.9 / clc-go-cli-v0.9` or `clc-java-sdk-v0.9`  within java-sdk ?

**Comment by push1st1k** [comment]
@pslam I think, it should be `clc-java-sdk-v1.2.0`

**Comment by idrabenia** [comment]
Awesome!

Thank you :)
