### ISSUE TITLE
Claim network response has changed

### ISSUE THREAD

**Issue by khomco** [CenturyLinkCloud/clc-java-sdk#200]
Currently the NetworkClient marshals the response of the claim of a network as follows:

```java
experimentalClient("/networks/{accountAlias}/{dataCenterId}/claim")
                .resolveTemplate(DATACENTER_ID, dataCenterId)
                .request()
                .post(entity(new HashMap<>(), APPLICATION_JSON_TYPE))
                .readEntity(Link.class);
```
which expects the API to return JSON like the following:

```json
{
      "rel":"status",
      "href":"/v2/operations/alias/status/wa1-12345",
      "id":"wa1-12345"
}
```

However, the API has changed to the following form of response 
(https://www.ctl.io/api-docs/v2/#networks-claim-network):

```json
{
  "operationId": "c387aa9873ab4f7399ea8964dd61510d",
  "uri": "/v2-experimental/operations/{accountAlias}/status/{operationId}"
}
```

**Note that the status URL is against the v2-experimental API**

**Comment by push1st1k** [comment]
fixed https://github.com/CenturyLinkCloud/clc-java-sdk/commit/18ac066bcc807200360f312829a44eaa2067d949
