### ISSUE TITLE
Gradle build fails

### ISSUE THREAD

**Issue by dirtdad** [CenturyLinkCloud/clc-java-sdk#209]
Upon doing a gradle build, I get this error

.
.
.
:sdk:javadoc UP-TO-DATE
:sdk:javadocJar UP-TO-DATE
:sdk:sourcesJar UP-TO-DATE
:sdk:signArchives

FAILURE: Build failed with an exception.
- What went wrong:
  Neither path nor baseDir may be null or empty string. path='' basedir='/home/resolve/clc-java-sdk/sdk'
- Try:
  Run with --info or --debug option to get more log output.
- Exception is:
  java.lang.IllegalArgumentException: Neither path nor baseDir may be null or empty string. path='' basedir='/home/resolve/clc-java-sdk/sdk'
      at org.gradle.api.internal.file.BaseDirFileResolver.doResolve(BaseDirFileResolver.java:65)
      at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:81)
      at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:63)

.
.
.
I am doing a search on this, but no luck yet. Do you have any suggestions about what to try next to fix this?

**Comment by ckleban** [comment]
Hello, we will take a look at get back to you soon...

thanks
Chris

**Comment by push1st1k** [comment]
Hello @dirtdad!

As I understand, you'd like to build SDK from sources. Gradle `build` contains a task for publishing SDK to maven repository. 
To fix this issue, please open `/sdk/build.gradle` and comment line `apply from: ./publishing.gradle`.
Or you may pull the latest sources from the repo.

Thanks,
Alex
